# Keep in sync with headers/version.h
VERSION     = 2.3.3

CC          ?= gcc
STD         = -std=gnu11
WARN        = -Wall -Wextra -Wformat-truncation=2 -Wshadow -Wwrite-strings
CFLAGS      ?= -march=native -O3 -pipe
UNIV_CFLAGS = -march=x86-64 -mtune=generic -O2 -pipe

ALL_CFLAGS  = $(STD) $(WARN) $(CFLAGS) -Iheaders -MMD -MP

SRC_DIR     = src
HDR_DIR     = headers
BUILD_DIR   = build
BIN_DIR     = bin
DIST_DIR    = dist

TARGET      = $(BIN_DIR)/emerge
DIST_BIN    = $(DIST_DIR)/emerge
DIST_ARCHIVE= $(DIST_DIR)/archtoo-v$(VERSION)-linux-x86_64.tar.gz

DESTDIR     ?=
PREFIX      ?= /usr/local
BINDIR      ?= $(PREFIX)/bin

SRCS        = $(SRC_DIR)/main.c \
              $(SRC_DIR)/cli.c \
              $(SRC_DIR)/guide.c \
              $(SRC_DIR)/config.c \
              $(SRC_DIR)/aur_rpc.c \
              $(SRC_DIR)/graph.c \
              $(SRC_DIR)/search.c \
              $(SRC_DIR)/package_info.c \
              $(SRC_DIR)/pkgbuild.c \
              $(SRC_DIR)/orphans.c \
              $(SRC_DIR)/cache.c \
              $(SRC_DIR)/stats.c \
              $(SRC_DIR)/news.c \
              $(SRC_DIR)/completion.c \
              $(SRC_DIR)/repo.c \
              $(SRC_DIR)/provider.c \
              $(SRC_DIR)/transaction.c \
              $(SRC_DIR)/dependency.c \
              $(SRC_DIR)/review.c \
              $(SRC_DIR)/devel.c \
              $(SRC_DIR)/upgrade.c \
              $(SRC_DIR)/utils.c \
              $(SRC_DIR)/world.c \
              $(SRC_DIR)/kernel.c \
              $(SRC_DIR)/unmerge.c \
              $(SRC_DIR)/build.c \
              $(SRC_DIR)/gentoo_chroot.c

OBJS        = $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS))
DEPS        = $(OBJS:.o=.d)

all: $(TARGET)

$(BUILD_DIR) $(BIN_DIR):
	mkdir -p $@

# Native build for local use (-march=native)
$(TARGET): $(OBJS) | $(BIN_DIR)
	$(CC) $(ALL_CFLAGS) -o $@ $(OBJS)
	@echo "[+] Native binary built at $@"

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(ALL_CFLAGS) -c $< -o $@

# Header dependencies generated by -MMD -MP, so touching headers/config.h
# actually triggers a rebuild.
-include $(DEPS)

# Portable build for a GitHub release (.tar.gz)
dist:
	mkdir -p $(DIST_DIR)
	$(CC) $(STD) $(WARN) $(UNIV_CFLAGS) -Iheaders $(SRCS) -o $(DIST_BIN)
	tar -czf $(DIST_ARCHIVE) -C $(DIST_DIR) emerge
	rm -f $(DIST_BIN)
	@echo "[+] Release archive built at $(DIST_ARCHIVE)"

# Strict pass used in CI
test-graph:
	$(CC) $(STD) $(WARN) -Wpedantic -Werror -O2 -Iheaders \
		tests/test_graph.c src/graph.c -o /tmp/archtoo-test-graph
	/tmp/archtoo-test-graph
	rm -f /tmp/archtoo-test-graph

test-aur-rpc:
	$(CC) $(STD) $(WARN) -Wpedantic -Werror -O2 -Iheaders \
		tests/test_aur_rpc.c src/aur_rpc.c -o /tmp/archtoo-test-aur-rpc
	/tmp/archtoo-test-aur-rpc
	rm -f /tmp/archtoo-test-aur-rpc

check:
	$(CC) $(STD) $(WARN) -Wpedantic -Werror -O2 -Iheaders -fsyntax-only $(SRCS)
	$(MAKE) test-graph
	@echo "[+] No warnings; graph tests passed"

clean:
	rm -rf $(BUILD_DIR) $(BIN_DIR) $(DIST_DIR)
	@echo "[+] Build directories cleaned"

# No sudo inside the recipe: run "sudo make install" yourself.
# This keeps DESTDIR-based packaging and CI working.
install: $(TARGET)
	install -Dm755 $(TARGET) $(DESTDIR)$(BINDIR)/emerge
	@echo "[+] Installed to $(DESTDIR)$(BINDIR)/emerge"

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/emerge
	@echo "[-] Removed from $(DESTDIR)$(BINDIR)/emerge"

.PHONY: all clean install uninstall dist check test-graph test-aur-rpc
